on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Clippy

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v6
      - run: rustup component add --toolchain nightly-2026-02-27-x86_64-unknown-linux-gnu clippy
      - run: cargo clippy --all-features --all-targets
