on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: No-Std Build

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  no_std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-generate --locked
      - run: cargo generate --git https://github.com/gregorygaines/cortex-m-quickstart -n nostd-app
      - run: rustup target add thumbv7em-none-eabihf
      - run: |
          cd nostd-app
          cargo add bitfields --path ../bitfields --package nostd-app
      - run: cargo build --target thumbv7em-none-eabihf